### ISSUE TITLE
set soldout buttons for soldout conference & soldout workshops

### ISSUE THREAD

**Issue by samvloeberghs** [ng-be/www-ng-be-org#3]

**Comment by SamVerschueren** [comment]
Should we just update the `Tickets available` buttons to `Join waitinglist`?

<img width="1150" alt="screen shot 2017-12-04 at 20 52 42" src="https://user-images.githubusercontent.com/1913805/33573104-28475c6e-d935-11e7-9d62-e249fbc7577f.png">

**Comment by samvloeberghs** [comment]
Ok!

Met vriendelijke groeten
Kind regards
Bien cordialement

— *Sam Vloeberghs*

(e) sam.vloeberghs@gmail.com
(t)  +32 (0)494 59 44 60

twitter.com/samvloeberghs

*Kwerri BVBA - http://kwerri.be <http://kwerri.be/>*

*Innovatus BVBA - http://innovatus.be <http://innovatus.be/>*
